replicaCount: 1

image:
  repository: bannukondeti/counterapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090
  targetPort: 9090
  nodePort: 30001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
