apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-counterapp
  labels:
    app: counterapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: counterapp
  template:
    metadata:
      labels:
        app: counterapp
    spec:
      containers:
      - name: counterapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
